[package]
name = "ark-zkey"
version = "0.1.1"
edition = "2021"
description = "Library to read zkey faster by serializing to arkworks friendly format."
license = "MIT OR Apache-2.0"
repository = "https://github.com/zkmopro/ark-zkey"
documentation = "https://zkmopro.org/"
homepage = "https://zkmopro.org/"
exclude = ["target/*", "test-vectors/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "arkzkey-util"
path = "src/bin/arkzkey_util.rs"

[dependencies]
color-eyre = "0.6"
memmap2 = "0.9"
flame = "0.2"
flamer = "0.5"

ark-serialize = { version = "0.5.0", features = ["derive"] }
ark-bn254 = { version = "0.5.0" }
ark-groth16 = { version = "0.5.0", features = ["parallel"] }
ark-circom = { version = "0.5.0"}
ark-relations = { version = "0.5.0" }
ark-ff = { version = "0.5.0" }
ark-ec = { version = "0.5.0", features = ["parallel"] }
